export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILURE = "REGISTRATION_FAILURE";
export const SET_REGISTRATION = "SET_REGISTRATION";
export const SET_TODO = "SET_TODO";
export const UPDATE_TODO = "UPDATE_TODO"
export const SET_USERS = 'SET_USERS'
